### ISSUE TITLE
prometheus dashboard with USE priciple

### ISSUE THREAD

**Issue by jamesWsg** [feiskyer/linux-perf-examples#1]
i am sorry to communicate with you in such a way，this is the only way i can found，i will use chinese following for convenience

在 极客时间 订阅了您的 linux 性能优化专栏，受益匪浅。

最近有个想法，在做性能监控时，一般会按照 USE的原则来实施，最近也刚接触到prometheus监控系统，参考过一些其他人的监控模板，链接如下：https://grafana.com/dashboards/8919 ，但是这个dashboard看起来并没有按照 USE的原则来组织。

因为了解到您也参与到kubernet的社区中，prometheus和kubernet联系也比较紧密，所以才 冒昧的向您 请教，不知道 您 那边是否有更好的类似的监控模板？ 或者您有其他更好的建议。（目标是 在回溯性能问题时，能够直观的判断出原因）

我相信这个如果有个比较权威的模板供参考，会节省不少相关技术人员的时间。不胜感激！

**Comment by feiskyer** [comment]
试试 prometheus-operator 的 dashboard？链接在 [这里](https://github.com/helm/charts/tree/master/stable/prometheus-operator/templates/grafana/dashboards).

**Comment by jamesWsg** [comment]
感谢回复，链接里面内容看起来有点多，我得 消化下，这个  prometheus-operator看起来完全是另一套比较复杂的体系。 我得先摸索下，不知道 最终的 效果会是啥样？  anyway，thank you very much
