### ISSUE TITLE
OOM killer基于虚拟内存?

### ISSUE THREAD

**Issue by leviathan0992** [feiskyer/linux-perf-examples#2]
@feiskyer 你好, 在<<Linux性能优化实战>> 22讲，有人提问: OOM 是按照虚拟内存还是实际内存来打分?

你的回答是:
> OOM 触发的时机基于虚拟内存。换句话说，进程在申请内存时，如果申请的虚拟内存加上服务器实际已用的内存之和，比总的物理内存还大，就会触发OOM。

这个回答应该是错误的，Linux本身就采用延迟分配的策略，申请的虚拟内存并不能等于实际物理内存，OOM的计数规则应该是对应实际的物理内存. 之前自己总结过一篇博客关于[Linux内核源码分析-理解cgroup内存资源控制](http://leviathan.vip/2019/09/01/Linux%E5%86%85%E6%A0%B8%E6%BA%90%E7%A0%81%E5%88%86%E6%9E%90-%E7%90%86%E8%A7%A3%E5%86%85%E5%AD%98%E8%B5%84%E6%BA%90%E6%8E%A7%E5%88%B6%E5%99%A8cgroup/#%E7%90%86%E8%A7%A3cgroup%E5%86%85%E5%AD%98%E8%AE%B0%E8%B4%A6)，在里面分析了关于分配访问文件分配物理Page的`cgroup`计数，只有在`page_alloc()`申请物理页成功的情况下，`cgroup`才成功计数, 所以OOM killer应该是基于物理内存的，而不是虚拟内存.

我的分析:
[OOM killer是基于虚拟内存还是物理内存?
](http://leviathan.vip/2019/10/05/OOM-killer%E6%98%AF%E5%9F%BA%E4%BA%8E%E8%99%9A%E6%8B%9F%E5%86%85%E5%AD%98%E8%BF%98%E6%98%AF%E7%89%A9%E7%90%86%E5%86%85%E5%AD%98/)

**Comment by feiskyer** [comment]
嗯嗯，谢谢指出，分析的很有道理。
