### ISSUE TITLE
[confused] About Memory Analyze

### ISSUE THREAD

**Issue by Belyenochi** [feiskyer/linux-perf-examples#3]
Env:
kernel 3.10 
os centos7

Description:
倪前辈，我在学习了贵专栏后解决实际问题过程中遇到了无从分析OOM的问题，还请老师指教思路

![lALPDgQ9rB2KZT3NAt7NBt0_1757_734](https://user-images.githubusercontent.com/26409132/66363182-f3cb8880-e9b7-11e9-8065-1a962e4a1a28.png)
我的思路如下：
1. 观察到在kernel cgroup代码中达到memory限制，查看memory组成
2. 查阅得知memory由rss + cache 组成，但是由图上得知cgroup对应进程和子进程的rss+cache 也未达到6291456KB，于是猜测如下
- 有尚未分析出的内存组成部分（好像加上kernel memory刚刚好）
  -kmem为啥这么高？？？泄漏？（但未在对应版本发现kernel memory leak bug）
- total-vm？？？？

还望倪前辈指教一二

**Comment by leviathan0992** [comment]
@Belyenochi OOM只考实际虑物理内存  total-vm是进程占用的虚拟内存大小，anon-rss是匿名页占用的物理内存大小.

**Comment by Belyenochi** [comment]
@Leviathan1995  cgoup oom在内核层面是计算kernel memory的，https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt

**Comment by Belyenochi** [comment]
@Leviathan1995 感谢
